[에러 수정] 내부 연결 안되는 링크 삭제
             Error: YAML Exception reading /home/runner/work/hanbijang.github.io/hanbijang.github.io/_posts/2022-04-01-새 포스트 쓰는 법.md: (<unknown>): did not find expected key while parsing a block mapping at line 2 column 1
                    done in 0.64 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
Running ["ScriptCheck", "LinkCheck", "ImageCheck", "HtmlCheck"] on ["_site"] on *.html...

- _site/posts/2022-04-01-새-포스트-쓰는-법/index.html
Ran on 11 files!
  *  linking to internal hash #image-path that does not exist (line 107)